import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AmbientBackground from "@/components/ui/AmbientBackground";
import AudioManager from "@/components/ui/AudioManager";
import { FocusProvider } from "@/context/FocusContext";
import FocusToggle from "@/components/ui/FocusToggle";
import FocusEditor from "@/components/ui/FocusEditor";
import { motion } from "framer-motion";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen text-gray-900 overflow-x-hidden`}
      >
        <FocusProvider>
          <AmbientBackground />
          <AudioManager />
          <FocusToggle />
          <motion.div
            animate={{
              filter: "none",
            }}
          >
            {children}
          </motion.div>
          <FocusEditor />
        </FocusProvider>
      </body>
    </html>
  );
}
